# -*- coding: utf-8 -*-
"""Computer Vision 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCEtkBRd37-i-Y_cA_N4Td3h6uF54FG_

## ส่วนใหม่
"""

!pip install opencv-python numpy matplotlib deepface

"""เชื่อมต่อ colab กับ google drive (Mount Drive)"""

from google.colab import drive
drive.mount("/content/drive")

# แสดง content ที่อยู่ใน drive
!ls /content/drive/MyDrive

# Set path ไฟล์รูปภาพ
path = '/content/drive/MyDrive/ComputerVisionUTCC/Images/'

# prompt: import cv2

import cv2
import matplotlib.pyplot as plt
image01 = cv2.imread(path + '/test.jpg')
assert image01 is not None, "file could not be read !!!"

print(image01.shape)
plt.imshow(image01)
plt.show()

# ปรับรูปจาก BGR เป็น RGB

import cv2
import matplotlib.pyplot as plt
image02 = cv2.imread(path + '/test.jpg')
assert image02 is not None, "file could not be read !!!"

print(image02.shape)
plt.imshow(cv2.cvtColor(image02, cv2.COLOR_BGR2RGB))
plt.show()

import cv2
import matplotlib.pyplot as plt
image03 = cv2.imread(path + '/OneFace.jpg')
assert image03 is not None, "file could not be read !!!"

print(image03.shape)
plt.imshow(cv2.cvtColor(image03, cv2.COLOR_BGR2RGB))
plt.show()

# แปลงรูปเป็น gray scale
gray_image= cv2.cvtColor(image03, cv2.COLOR_BGR2GRAY)
#plt.imshow(gray_image)
plt.imshow(cv2.cvtColor(gray_image, cv2.COLOR_BGR2RGB))
plt.show()

# Save ไฟล์รูปลง Drive
cv2.imwrite(path + 'grayed_OneFace.jpg', gray_image)

"""Blur ภาพ"""

blurred_image = cv2.GaussianBlur(image03,(145,145),0,0)
plt.imshow(cv2.cvtColor(blurred_image, cv2.COLOR_BGR2RGB))
plt.show()

blurred_image = cv2.GaussianBlur(image03,(45,45),0,0)
plt.imshow(cv2.cvtColor(blurred_image, cv2.COLOR_BGR2RGB))
plt.show()

"""ต่อภาพ ( Image Concatenation )"""

import numpy as np
#ต่อภาพในแนวนอน
numpy_horizontal_concat = np.concatenate((image03,blurred_image),axis=1)
plt.imshow(cv2.cvtColor(numpy_horizontal_concat, cv2.COLOR_BGR2RGB))
plt.show()

#ต่อภาพในแนวตั้ง
numpy_horizontal_concat1 = np.concatenate((image03,blurred_image),axis=0)
plt.imshow(cv2.cvtColor(numpy_horizontal_concat1, cv2.COLOR_BGR2RGB))

numpy_horizontal_concat2 = np.concatenate((blurred_image,image03),axis=0)
plt.imshow(cv2.cvtColor(numpy_horizontal_concat2, cv2.COLOR_BGR2RGB))

numpy_horizontal_concat_final = np.concatenate((numpy_horizontal_concat1,numpy_horizontal_concat2),axis=1)
plt.imshow(cv2.cvtColor(numpy_horizontal_concat_final, cv2.COLOR_BGR2RGB))
plt.show()
cv2.imwrite(path + 'numpy_horizontal_concat_final.jpg', numpy_horizontal_concat_final)

numpy_horizontal_concat = np.concatenate((image03,blurred_image),axis=0)
plt.imshow(cv2.cvtColor(numpy_horizontal_concat, cv2.COLOR_BGR2RGB))
plt.show()

"""Edge Detection"""

edges01 =cv2.Canny(gray_image, 100, 200)
plt.imshow(edges01, cmap='gray')
plt.show()

import cv2
import matplotlib.pyplot as plt
image04 = cv2.imread(path + '/MedicalImage.jpg')
assert image04 is not None, "file could not be read !!!"

print(image04.shape)
plt.imshow(cv2.cvtColor(image04, cv2.COLOR_BGR2RGB))
plt.show()

edges02 =cv2.Canny(image04, 100, 500)
plt.imshow(edges02, cmap='gray')
plt.show()

edge03 = cv2.Sobel(image04, cv2.CV_64F,1,0, ksize=5)
plt.imshow(edge03, cmap= 'gray')

"""Face Detection

Haar Classifier
"""

import cv2
import matplotlib.pyplot as plt

img01 = cv2.imread(path + 'TwoFaces01.jpg')
assert img01 is not None, "หาไฟล์ไม่เจอจ่ะ !!!"

print (img01.shape)
plt.imshow(cv2.cvtColor(img01, cv2.COLOR_BGR2RGB))
plt.show()

# ปรับให้เป็น gray scale
gray_img01 = cv2.cvtColor(img01, cv2.COLOR_BGR2GRAY)
plt.imshow(cv2.cvtColor(gray_img01, cv2.COLOR_BGR2RGB))
plt.show()

"""Load face classifier"""

face_classifier = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

"""ทำ face detection"""

face01 = face_classifier.detectMultiScale(gray_img01)
print(face01)
print("จำนวนใบหน้าที่ detect ได้ =", face01.shape[0])

"""ตีกรอบใบหน้า"""

for (x, y, w, h) in face01:
  cv2.rectangle(img01, (x, y), (x+w, y+h),
                               (0, 0, 255), 4)

img01_rgb = cv2.cvtColor(img01, cv2.COLOR_BGR2RGB)
#plt.figure(figsize=(20,10))
plt.imshow(img01_rgb)
plt.show()

import cv2
import matplotlib.pyplot as plt

img02 = cv2.imread(path + 'MultiFaces.jpg')
assert img02 is not None, "หาไฟล์ไม่เจอจ่ะ !!!"

print (img02.shape)
plt.imshow(cv2.cvtColor(img02, cv2.COLOR_BGR2RGB))
plt.show()

gray_img02 = cv2.cvtColor(img02, cv2.COLOR_BGR2GRAY)
plt.imshow(cv2.cvtColor(gray_img02, cv2.COLOR_BGR2RGB))
plt.show()

face_classifier = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

face02 = face_classifier.detectMultiScale(gray_img02)
print(face02)
print("จำนวนใบหน้าที่ detect ได้ =", face02.shape[0])

for (x, y, w, h) in face02:
  cv2.rectangle(img02, (x, y), (x+w, y+h),
                               (0, 0, 255), 4)

img02_rgb = cv2.cvtColor(img02, cv2.COLOR_BGR2RGB)
#plt.figure(figsize=(20,10))
plt.imshow(img02_rgb)
plt.show()

"""การ detect อารมณ์ของใบหน้า"""

!pip install deepface

import cv2
from deepface import DeepFace
import matplotlib.pyplot as plt

img03 = cv2.imread(path + 'OneFace.jpg')
result = DeepFace.analyze(img_path=path+'OneFace.jpg',enforce_detection=False)
print(result[0]['dominant_emotion'])

plt.imshow(cv2.cvtColor(img03, cv2.COLOR_BGR2RGB))
plt.show()